### PR TITLE
Ansible collection

### LINKED ISSUE #1: Install as a Ansible collection
It would be great to be able to install these modules/plugins as a Ansible collection with ansible-galaxy as opposed to pip.

Helpful links:
https://docs.ansible.com/ansible/latest/user_guide/collections_using.html
https://docs.ansible.com/ansible/latest/dev_guide/developing_collections.html

### PR DESCRIPTION
**Pull request by gardar**
This converts the plugins into a ansible collection and fixes #1 

By converting them into a collection they can be directly installed with ansible galaxy, so there is no need for using pip and manually planting the plugins within roles.

`ansible-galaxy collection install git+https://github.com/netson/ahvl`
Or if the roles get published on ansible galaxy:
`ansible-galaxy collection install netson.ahvl`

After installing the collection the plugins can be referenced by fqcn:
`netson.ahvl.credential`
`netson.ahvl.gpgkey`
`netson.ahvl.password`
`netson.ahvl.set_password`
`netson.ahvl.sshhostkey`
`netson.ahvl.sshkey`

### CODE REVIEW

**Comment by gardar** [comment]
Also added a fix for libgcrypt versioning regex that was failing on my setup
The string on my setup is not just numeric: libgcrypt 1.9.4-unknown

**Comment by gardar** [comment]
Have you had a change to give this a try @netson ?

If you want to try it you can install it from my fork with ansible-galaxy like this:
`ansible-galaxy collection install git+https://github.com/gardar/ahvl.git,ansible-collection`

**Comment by netson** [comment]
Hey @gardar,

thank you very much for this PR! I just haven't had the time to test it out yet. Code changes seem minimal, so I don't expect many problems, but I have been crazy busy lately so I am hesitant to play with this on a production system and setting up a test environment just takes some time. I will get back to you as soon as possible, but considering my workload at the moment and (hopefully) a short skitrip over the next couple of weeks, it may take about a month or so before I can actually properly test this.

I do see the value in this and have every intention of merging the PR if all works well, I'm just hoping for some patience.

Regards,
Rinck

**Comment by gardar** [comment]
@netson no worries, I wasn't sure you had seen the PR.
I've been playing around with some other changes as well which I wanted to add, but they depend on this PR.

You could test the changes by installing ansible and the collection in a python virtualenv, that way you wouldn't mess up your production setup.
But it might also perhaps be a good idea to add tests for the plugins? With ansible-test or molecule, then you could let github actions run the tests automatically, and perhaps do the galaxy publish as well in the action.

**Comment by gardar** [comment]
Any news @netson ?

**Comment by netson** [comment]
Hi @gardar, I do apologize for the extreme delay, it's been a crazy year for me. I have decided to no longer invest time in this package and will most likely switch from using Ansible to Jetporch. That means this 'middleware' will at some point in the future get a rewrite in Rust in one form or another. I'd be happy to handover the keys to this repository, if that helps you. Let me know!

**Pull request closed without merging**
